name: Release Main

on:
  workflow_dispatch:
    inputs:
      upload_packages:
        required: true
        description: "Upload packages to anaconda?"
        type: boolean

jobs:
  build:
    name: build (${{ matrix.python-version }}, ${{ matrix.platform.name }})
    runs-on: ${{ matrix.platform.os }}
    strategy:
      max-parallel: 9
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        platform:
          - { name: "linux", os: "ubuntu-latest", shell: "bash -l {0}" }
          - { name: "macos", os: "macos-latest", shell: "bash -l {0}" }
        exclude:
          - platform:
              { name: "macos", os: "macos-latest", shell: "bash -l {0}" }
            python-version: "3.12"  #Â MacOS can't run 3.12 yet...
    environment:
      name: ghostly-build
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}
    env:
      SIRE_DONT_PHONEHOME: 1
      SIRE_SILENT_PHONEHOME: 1
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: ghostly_build
          miniforge-version: latest
#
      - name: Clone the main branch
        run: git clone -b main https://github.com/openbiosim/ghostly
#
      - name: Setup Conda
        run: conda install -y -c conda-forge boa anaconda-client packaging
#
      - name: Update Conda recipe
        run: python ${{ github.workspace }}/ghostly/actions/update_recipe.py
#
      - name: Prepare build location
        run: mkdir ${{ github.workspace }}/build
#
      - name: Build Conda package using conda build
        run: conda build -c conda-forge -c openbiosim/label/main ${{ github.workspace }}/ghostly/recipes/ghostly
#
      - name: Upload Conda package
        run: python ${{ github.workspace }}/ghostly/actions/upload_package.py
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
          ANACONDA_LABEL: main
        if: github.event.inputs.upload_packages == 'true' && matrix.platform.name == 'linux' && matrix.python-version == '3.11'
